#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="${SCRIPT_DIR}/templates"

DOCKER_USER="${DOCKER_USER:-docker}"
DOCKER_HOME="${DOCKER_HOME:-/home/${DOCKER_USER}}"
DEPLOY_DIR="${DEPLOY_DIR:-${DOCKER_HOME}/deploy}"

FORCE=0
START_STACK=0
PULL_IMAGES=0

usage() {
  cat <<'EOF'
Usage: configure-stack.sh [--force] [--start] [--pull]

  --force   overwrite existing template-managed files
  --start   validate env files, login to GHCR if configured, and start services
  --pull    pull images before starting the stack
EOF
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "Run as root." >&2
    exit 1
  fi
}

log() {
  printf '\n[%s] %s\n' "$(date -u +%H:%M:%S)" "$*"
}

docker_uid() {
  id -u "${DOCKER_USER}"
}

docker_runtime_dir() {
  printf '/run/user/%s\n' "$(docker_uid)"
}

docker_env() {
  env \
    HOME="${DOCKER_HOME}" \
    XDG_RUNTIME_DIR="$(docker_runtime_dir)" \
    DOCKER_HOST="unix://$(docker_runtime_dir)/docker.sock"
}

copy_if_missing_or_forced() {
  local src="$1"
  local dst="$2"
  local mode="$3"

  if [[ -e "${dst}" && "${FORCE}" -ne 1 ]]; then
    return
  fi

  install -D -m "${mode}" "${src}" "${dst}"
}

render_template() {
  local src="$1"
  local dst="$2"
  local mode="$3"

  if [[ -e "${dst}" && "${FORCE}" -ne 1 ]]; then
    return
  fi

  sed \
    -e "s|__DOCKER_HOME__|${DOCKER_HOME}|g" \
    -e "s|__DOCKER_UID__|$(docker_uid)|g" \
    "${src}" >"${dst}"
  chmod "${mode}" "${dst}"
}

assert_no_placeholders() {
  local file="$1"
  if grep -q '__REQUIRED__' "${file}"; then
    echo "Replace placeholder values in ${file} before --start." >&2
    exit 1
  fi
}

install_stack_files() {
  install -d -m 0755 -o "${DOCKER_USER}" -g "${DOCKER_USER}" "${DEPLOY_DIR}/caddy" "${DEPLOY_DIR}/state"
  install -d -m 0755 -o "${DOCKER_USER}" -g "${DOCKER_USER}" "${DOCKER_HOME}/.config/systemd/user"

  copy_if_missing_or_forced "${TEMPLATES_DIR}/deploy/compose.yaml" "${DEPLOY_DIR}/compose.yaml" 0644
  copy_if_missing_or_forced "${TEMPLATES_DIR}/deploy/caddy/Caddyfile" "${DEPLOY_DIR}/caddy/Caddyfile" 0644
  copy_if_missing_or_forced "${TEMPLATES_DIR}/deploy/caddy/app-deploy-holding.html" "${DEPLOY_DIR}/caddy/app-deploy-holding.html" 0644
  copy_if_missing_or_forced "${TEMPLATES_DIR}/deploy/images.env.example" "${DEPLOY_DIR}/images.env.example" 0644
  copy_if_missing_or_forced "${TEMPLATES_DIR}/deploy/proxy.env.example" "${DEPLOY_DIR}/proxy.env.example" 0644
  copy_if_missing_or_forced "${TEMPLATES_DIR}/deploy/registry.env.example" "${DEPLOY_DIR}/registry.env.example" 0644
  copy_if_missing_or_forced "${TEMPLATES_DIR}/deploy/app.env.example" "${DEPLOY_DIR}/app.env.example" 0644
  copy_if_missing_or_forced "${TEMPLATES_DIR}/deploy/api.env.example" "${DEPLOY_DIR}/api.env.example" 0644
  render_template "${TEMPLATES_DIR}/docker-user/swift-stack.service" "${DOCKER_HOME}/.config/systemd/user/swift-stack.service" 0644

  [[ -f "${DEPLOY_DIR}/images.env" ]] || install -m 0600 "${TEMPLATES_DIR}/deploy/images.env.example" "${DEPLOY_DIR}/images.env"
  [[ -f "${DEPLOY_DIR}/proxy.env" ]] || install -m 0600 "${TEMPLATES_DIR}/deploy/proxy.env.example" "${DEPLOY_DIR}/proxy.env"
  [[ -f "${DEPLOY_DIR}/registry.env" ]] || install -m 0600 "${TEMPLATES_DIR}/deploy/registry.env.example" "${DEPLOY_DIR}/registry.env"
  [[ -f "${DEPLOY_DIR}/app.env" ]] || install -m 0600 "${TEMPLATES_DIR}/deploy/app.env.example" "${DEPLOY_DIR}/app.env"
  [[ -f "${DEPLOY_DIR}/api.env" ]] || install -m 0600 "${TEMPLATES_DIR}/deploy/api.env.example" "${DEPLOY_DIR}/api.env"
  [[ -f "${DEPLOY_DIR}/caddy/cloudflare-trusted-proxies.caddy" ]] || printf '# generated by /usr/local/sbin/update-cloudflare-nft-sets\n' >"${DEPLOY_DIR}/caddy/cloudflare-trusted-proxies.caddy"

  chown -R "${DOCKER_USER}:${DOCKER_USER}" "${DEPLOY_DIR}" "${DOCKER_HOME}/.config/systemd/user"
}

reload_user_units() {
  local runtime_dir
  runtime_dir="$(docker_runtime_dir)"
  systemctl start "user@$(docker_uid).service"
  runuser -u "${DOCKER_USER}" -- env XDG_RUNTIME_DIR="${runtime_dir}" systemctl --user daemon-reload
}

refresh_cloudflare_data() {
  if [[ -x /usr/local/sbin/update-cloudflare-nft-sets ]]; then
    /usr/local/sbin/update-cloudflare-nft-sets
  fi
}

ghcr_login() {
  local runtime_dir
  runtime_dir="$(docker_runtime_dir)"

  if grep -q '__REQUIRED__' "${DEPLOY_DIR}/registry.env"; then
    echo "Skipping GHCR login: registry.env still has placeholders."
    return
  fi

  runuser -u "${DOCKER_USER}" -- env XDG_RUNTIME_DIR="${runtime_dir}" DOCKER_HOST="unix://${runtime_dir}/docker.sock" \
    bash -lc '
      set -euo pipefail
      cd "'"${DEPLOY_DIR}"'"
      set -a
      source ./registry.env
      set +a
      printf "%s\n" "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
    '
}

start_stack() {
  local runtime_dir
  runtime_dir="$(docker_runtime_dir)"

  assert_no_placeholders "${DEPLOY_DIR}/images.env"
  assert_no_placeholders "${DEPLOY_DIR}/proxy.env"
  assert_no_placeholders "${DEPLOY_DIR}/app.env"
  assert_no_placeholders "${DEPLOY_DIR}/api.env"

  ghcr_login

  if [[ "${PULL_IMAGES}" -eq 1 ]]; then
    runuser -u "${DOCKER_USER}" -- env XDG_RUNTIME_DIR="${runtime_dir}" DOCKER_HOST="unix://${runtime_dir}/docker.sock" \
      docker compose --env-file "${DEPLOY_DIR}/images.env" -f "${DEPLOY_DIR}/compose.yaml" pull
  fi

  runuser -u "${DOCKER_USER}" -- env XDG_RUNTIME_DIR="${runtime_dir}" systemctl --user enable --now docker.service swift-stack.service
  runuser -u "${DOCKER_USER}" -- env XDG_RUNTIME_DIR="${runtime_dir}" systemctl --user restart swift-stack.service
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --force)
        FORCE=1
        ;;
      --start)
        START_STACK=1
        ;;
      --pull)
        PULL_IMAGES=1
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        echo "Unknown argument: $1" >&2
        usage >&2
        exit 1
        ;;
    esac
    shift
  done
}

main() {
  require_root
  parse_args "$@"

  log "Installing stack templates into ${DEPLOY_DIR}"
  install_stack_files

  log "Reloading docker user units"
  reload_user_units

  log "Refreshing Cloudflare-generated files"
  refresh_cloudflare_data

  if [[ "${START_STACK}" -eq 1 ]]; then
    log "Starting the application stack"
    start_stack
  else
    cat <<EOF

Stack files installed.

Before starting:
  1. Edit ${DEPLOY_DIR}/images.env
  2. Edit ${DEPLOY_DIR}/proxy.env
  3. Edit ${DEPLOY_DIR}/app.env
  4. Edit ${DEPLOY_DIR}/api.env
  5. Optionally edit ${DEPLOY_DIR}/registry.env

Then run:
  ${SCRIPT_DIR}/configure-stack.sh --start --pull
EOF
  fi
}

main "$@"
