#!/usr/sbin/nft -f

include "/etc/nftables.d/cloudflare-ips.nft"

destroy table inet hostfilter
destroy table ip6 dockernat

table inet hostfilter {
    chain input {
        type filter hook input priority filter; policy drop;

        ct state invalid drop
        ct state established,related accept
        iifname "lo" accept

        ip protocol icmp accept
        ip6 nexthdr ipv6-icmp accept

        iifname "tailscale0" tcp dport 22 accept

        ip saddr $cloudflare_ipv4 tcp dport { 80, 443 } accept
        ip6 saddr $cloudflare_ipv6 tcp dport { 80, 443 } accept
    }

    chain forward {
        type filter hook forward priority filter; policy drop;

        ct state invalid drop
        ct state established,related accept
        iifname "docker0" accept
        iifname "br-*" accept
        oifname "docker0" ct state established,related accept
        oifname "br-*" ct state established,related accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}

table ip6 dockernat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;

        ip6 saddr { fd00:dead:beef::/64, fd00:deaf:cafe::/48 } oifname != "docker0" oifname != "br-*" masquerade
    }
}
